# Generated by Django 5.2.8 on 2025-11-30 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('short_description', models.TextField(help_text='Displayed on cards')),
                ('description', models.TextField(help_text='Full description for the property page')),
                ('image', models.ImageField(blank=True, null=True, upload_to='properties/')),
                ('price_from', models.DecimalField(decimal_places=2, max_digits=10)),
                ('beds', models.IntegerField()),
                ('baths', models.IntegerField()),
                ('capacity', models.IntegerField(help_text='Maximum number of guests')),
                ('parking', models.BooleanField(default=False)),
                ('distance_to_stadium_mins', models.IntegerField(default=0, help_text='Minutes to stadium')),
                ('tags', models.CharField(blank=True, help_text='Comma separated tags', max_length=500)),
                ('keywords', models.TextField(blank=True, help_text='Keywords for search optimization')),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Properties',
            },
        ),
    ]
