# Generated by Django 5.2.8 on 2025-12-04 22:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yourapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guesty_reservation_id', models.CharField(blank=True, db_index=True, help_text='Guesty reservation ID for sync', max_length=100, null=True)),
                ('stripe_session_id', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('guest_name', models.CharField(max_length=200)),
                ('guest_email', models.EmailField(max_length=254)),
                ('guest_phone', models.CharField(blank=True, max_length=50)),
                ('check_in', models.DateField(db_index=True)),
                ('check_out', models.DateField()),
                ('guests', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('inquiry', 'Inquiry'), ('pending', 'Pending'), ('confirmed', 'Confirmed'), ('canceled', 'Canceled'), ('completed', 'Completed')], default='inquiry', max_length=20)),
                ('source', models.CharField(choices=[('direct', 'Direct Website'), ('guesty', 'Guesty'), ('airbnb', 'Airbnb'), ('booking', 'Booking.com'), ('vrbo', 'VRBO'), ('other', 'Other')], default='direct', max_length=20)),
                ('nightly_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cleaning_fee', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('guest_notes', models.TextField(blank=True, help_text='Notes from the guest')),
                ('internal_notes', models.TextField(blank=True, help_text='Internal staff notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='yourapp.property')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-check_in'],
                'indexes': [models.Index(fields=['property', 'check_in'], name='yourapp_boo_propert_69ea25_idx'), models.Index(fields=['status', 'check_in'], name='yourapp_boo_status_4e7704_idx')],
            },
        ),
    ]
