# Generated by Django 5.2.8 on 2025-12-04 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yourapp', '0003_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='receipt_pdf',
            field=models.FileField(blank=True, null=True, upload_to='receipts/'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('inquiry', 'Inquiry'), ('awaiting_payment', 'Awaiting Payment'), ('pending', 'Pending'), ('confirmed', 'Confirmed'), ('canceled', 'Canceled'), ('completed', 'Completed')], default='inquiry', max_length=20),
        ),
    ]
