# Generated by Django 6.0 on 2025-12-29 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yourapp', '0005_alter_booking_id_alter_profile_id_alter_property_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='homepage_order',
            field=models.IntegerField(default=0, help_text='Order in Top Properties section (lower numbers appear first)'),
        ),
        migrations.AddField(
            model_name='property',
            name='show_on_homepage',
            field=models.BooleanField(default=False, help_text='Display in Top Properties section on homepage'),
        ),
    ]
