# Generated by Django 5.2.8 on 2026-01-13 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yourapp', '0006_property_homepage_order_property_show_on_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='company_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='company_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='booking',
            name='company_vat',
            field=models.CharField(blank=True, help_text='VAT/Tax registration number', max_length=50),
        ),
        migrations.AddField(
            model_name='booking',
            name='is_company_booking',
            field=models.BooleanField(default=False),
        ),
    ]
