# Generated by Django 5.2.8 on 2026-01-13 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yourapp', '0007_add_company_booking_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='account_type',
            field=models.CharField(choices=[('personal', 'Personal'), ('business', 'Business')], default='personal', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='company_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='company_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='company_registration_number',
            field=models.CharField(blank=True, help_text='Company registration number', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='company_vat',
            field=models.CharField(blank=True, help_text='VAT/Tax registration number', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='job_title',
            field=models.CharField(blank=True, help_text='Your role/job title at the company', max_length=100),
        ),
    ]
