# Generated by Django 6.0 on 2026-01-15 10:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yourapp', '0008_add_business_account_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('subtitle', models.CharField(blank=True, help_text="E.g., 'Near the stadium'", max_length=200)),
                ('icon_name', models.CharField(default='location', help_text='Icon identifier: location, stadium, city, home, park, nearby', max_length=50)),
                ('icon_color', models.CharField(default='#2E7D32', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('filter_area', models.CharField(blank=True, help_text='Area value to filter properties (leave blank for all)', max_length=100)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='property',
            name='area',
            field=models.CharField(default='Sheffield', help_text='Area/neighborhood name (e.g., City Centre, Hillsborough)', max_length=100),
        ),
        migrations.AddField(
            model_name='property',
            name='city',
            field=models.CharField(default='Sheffield', max_length=100),
        ),
        migrations.AddField(
            model_name='property',
            name='postcode',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.CreateModel(
            name='RecentSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=40)),
                ('location', models.CharField(max_length=200)),
                ('check_in', models.DateField(blank=True, null=True)),
                ('check_out', models.DateField(blank=True, null=True)),
                ('guests', models.PositiveIntegerField(default=2)),
                ('searched_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recent_searches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Recent searches',
                'ordering': ['-searched_at'],
            },
        ),
    ]
