# Generated by Django 5.2.8 on 2026-01-17 17:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yourapp', '0009_destination_property_area_property_city_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='booking',
            name='yourapp_boo_propert_69ea25_idx',
        ),
        migrations.AlterField(
            model_name='booking',
            name='property',
            field=models.ForeignKey(db_column='property_id', on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='yourapp.property'),
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='property',
            new_name='booked_property',
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['booked_property', 'check_in'], name='yourapp_boo_propert_69ea25_idx'),
        ),
    ]
